# Generated by Django 2.0.1 on 2018-01-21 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infed', '0002_auto_20180120_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='certificate_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='entity_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
